# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node_version: [10.x]

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: ${{ matrix.node_version }}
      
    - name: Checkout
      uses: actions/checkout@v2
            
    - name: Run build
      run: sh package.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
        
    - name: Tag
      uses: mathieudutour/github-tag-action@v4.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
